# Github Action pipeline that runs on push to main branch
# Docker build and push the album-api image to ACR

name: pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image
      run: |
        docker build -t album-api .
        docker tag album-api ${{ secrets.ACR_NAME }}.azurecr.io/album-api
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/album-api
        docker tag album-api "${{ secrets.DOCKER_HUB_USERNAME }}/album-api:${{ github.run_id }}"
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/album-api:${{ github.run_id }}

#run tests on the album-api image
    - name: Run tests
      run: |
        docker run -d -p 8080:8080 --name album-api ${{ secrets.ACR_NAME }}.azurecr.io/album-api
        sleep 10
        curl -X GET http://localhost:8080/albums
        docker stop album-api
        docker rm album-api

    - name: Logout of Azure
      run: |
        az logout

    - name: Logout of Docker Hub
      run: |
        docker logout

